Arch:
  name: enet
  num_classes: 4
Augment:
  crop_size: 128
  resize_size: 192
DataLoader:
  drop_last: false
  labeled_batch_size: 4
  num_workers: 6
  pin_memory: false
  shuffle: true
  unlabeled_batch_size: 4
  val_batch_size: 1
Dataset:
  labeled_data_ratio: 0.05
  name: acdc
  unlabeled_data_ratio: 0.95
Optim:
  lr: 0.0001
  momentum: 0.9
  name: SGD
  nesterov: true
  weight_decay: 0.0005
RegScheduler:
  begin_epoch: 10
  max_epoch: 30
  max_value: 0
  min_value: 0
  ramp_mult: -5
Scheduler:
  T_max: 90
  name: CosineAnnealingLR
  warmup:
    multiplier: 300
    total_epoch: 10
Trainer:
  device: cuda
  max_epoch: 100
  name: BaselineTrainer
  num_batches: 512
  report_axis:
  - 1
  - 2
  - 3
  save_dir: 0122/check_MT/ACDC/baseline
  track_bn: true
